resolver: lts-3.10

compiler: ghcjs-0.2.0.20151029_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
      source:
            ghcjs-0.2.0.20151029_ghc-7.10.2:
                    url: "https://github.com/nrolland/ghcjs/releases/download/v0.2.0.20151029/ghcjs-0.2.0.20151029.tar.gz"


packages:
- '.'
- '..'
- location: '../../servant/servant/'
  extra-dep: true
- location: '../../servant/servant-client/'
  extra-dep: true
- location: '../../servant/servant-server/'
  extra-dep: true
# - '../../servant/servant-blaze/'
# - '../../servant/servant-cassava/'
# - '../../servant/servant-docs/'
# - '../../servant/servant-examples/'
# - '../../servant/servant-foreign/'
# - '../../servant/servant-js/'
# - '../../servant/servant-lucid/'
# - '../../servant/servant-mock/'

extra-deps:
    - ghcjs-dom-0.2.3.1
    - http-api-data-0.2.2

nix:
    enable: false
    packages: [nodejs]
